[package]
name = "aptos-gas"
version = "0.1.0"
authors = ["Aptos Labs <opensource@aptoslabs.com>"]
description = "Gas metering for the Aptos blockchain"
repository = "https://github.com/aptos-labs/aptos-core"
homepage = "https://aptoslabs.com"
license = "Apache-2.0"
publish = false
edition = "2021"

[dependencies]
anyhow = "1.0.57"
bcs = "0.1.3"
clap = { version = "3.1.17", features = ["derive"] }

move-binary-format = { git = "https://github.com/move-language/move", rev = "058bff374d2dae4840037ff46aec8551387777da" }
move-core-types = { git = "https://github.com/move-language/move", rev = "058bff374d2dae4840037ff46aec8551387777da" }
move-model = { git = "https://github.com/move-language/move", rev = "058bff374d2dae4840037ff46aec8551387777da" }
move-stdlib = { git = "https://github.com/move-language/move", rev = "058bff374d2dae4840037ff46aec8551387777da" }
move-table-extension = { git = "https://github.com/move-language/move", rev = "058bff374d2dae4840037ff46aec8551387777da" }
move-vm-types = { git = "https://github.com/move-language/move", rev = "058bff374d2dae4840037ff46aec8551387777da" }

aptos-global-constants = { path = "../../config/global-constants" }
aptos-types = { path = "../../types" }
framework = { path = "../framework" }
gas-algebra-ext = { path = "../gas-algebra-ext" }
package-builder = { path = "../package-builder" }

[dev-dependencies]
tempfile = "3.3.0"

[features]
testing = ["move-stdlib/testing", "aptos-global-constants/testing"]

[[bin]]
name = "aptos-gas-gen-update-proposal"
path = "src/bin/gen_proposal.rs"
